baseURL = "https://statkwon.github.io"

languageCode = "en-us"
title = "ML Lab"
theme = "techdoc"
hasCJKLanguage = true

[params]
version = "1.0.0"
description = "STATKWON"
github_repository = "https://github.com/statkwon"
github_doc_repository = "https://github.com/statkwon/blog"
menu_style = "slide-menu"
menu_exclusion = ["projects"]

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Instagram"
        url = "https://www.instagram.com/kwon_leben/"
        weight = 2